'use client';

import React, { useRef } from 'react';
import generatePDF from 'react-to-pdf';

interface SimplePdfDownloadProps {
  content: string;
  title: string;
  template: string;
  className?: string;
}

export default function SimplePdfDownload({ content, title, template, className = '' }: SimplePdfDownloadProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    if (!contentRef.current) return;

    try {
      const options = {
        filename: `${title.replace(/[^a-zA-Z0-9]/g, '_')}_${template}_notes.pdf`,
      };

      await generatePDF(contentRef, options);
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  return (
    <div className={className}>
      {/* Content div for PDF generation */}
      <div 
        ref={contentRef} 
        style={{
          position: 'absolute',
          left: '-9999px',
          top: '-9999px',
          padding: '20px',
          fontFamily: 'Arial, sans-serif',
          fontSize: '12px',
          lineHeight: '1.5',
          maxWidth: '800px',
          margin: '0 auto',
          backgroundColor: 'white',
          color: 'black',
          width: '800px'
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: '20px' }}>
          <h1 style={{ fontSize: '18px', fontWeight: 'bold', marginBottom: '10px' }}>
            {title}
          </h1>
          <p style={{ fontSize: '14px', color: '#666', marginBottom: '20px' }}>
            Generated with {template} template
          </p>
          <hr style={{ border: '1px solid #ddd', marginBottom: '20px' }} />
        </div>
        
        <div 
          dangerouslySetInnerHTML={{ 
            __html: '<div>' + content
              .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
              .replace(/\*(.*?)\*/g, '<em>$1</em>')
              // Handle headers with emojis and complex formatting
              .replace(/^### (.*$)/gm, '</div><h3 style="font-size: 16px; font-weight: bold; margin-top: 15px; margin-bottom: 10px; color: #333;">$1</h3><div style="margin-bottom: 15px;">')
              .replace(/^## (.*$)/gm, '</div><h2 style="font-size: 18px; font-weight: bold; margin-top: 20px; margin-bottom: 15px; color: #333;">$1</h2><div style="margin-bottom: 15px;">')
              .replace(/^# (.*$)/gm, '</div><h1 style="font-size: 20px; font-weight: bold; margin-top: 25px; margin-bottom: 20px; color: #333;">$1</h1><div style="margin-bottom: 15px;">')
              // Handle bullet points and lists
              .replace(/^- (.*$)/gm, '<div style="margin-left: 20px; margin-bottom: 5px;">• $1</div>')
              .replace(/^1\. (.*$)/gm, '<div style="margin-left: 20px; margin-bottom: 5px;">1. $1</div>')
              .replace(/^2\. (.*$)/gm, '<div style="margin-left: 20px; margin-bottom: 5px;">2. $1</div>')
              .replace(/^3\. (.*$)/gm, '<div style="margin-left: 20px; margin-bottom: 5px;">3. $1</div>')
              .replace(/^4\. (.*$)/gm, '<div style="margin-left: 20px; margin-bottom: 5px;">4. $1</div>')
              .replace(/^5\. (.*$)/gm, '<div style="margin-left: 20px; margin-bottom: 5px;">5. $1</div>')
              // Handle line breaks
              .replace(/\n/g, '<br>')
              + '</div>'
          }} 
        />
        
        <div style={{ marginTop: '30px', paddingTop: '20px', borderTop: '1px solid #ddd', textAlign: 'center', fontSize: '10px', color: '#999' }}>
          <p>Generated by Kyoto Scribe 🐕</p>
          <p>{new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Download button */}
      <button
        onClick={handleDownload}
        className="inline-flex items-center px-3 py-2 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-lg transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 text-sm"
        disabled={!content}
      >
        <svg 
          className="w-4 h-4 mr-2" 
          fill="none" 
          stroke="currentColor" 
          viewBox="0 0 24 24"
        >
          <path 
            strokeLinecap="round" 
            strokeLinejoin="round" 
            strokeWidth={2} 
            d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" 
          />
        </svg>
        Download PDF
      </button>
    </div>
  );
}
