import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - KyotoScribe',
  description: 'Terms of Service for KyotoScribe AI video processing service',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-8">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
              Terms of Service
            </h1>
            <p className="text-gray-600 dark:text-gray-300">
              Last updated: September 2025
            </p>
          </div>

          <div className="prose prose-gray dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                By accessing and using KyotoScribe ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Description of Service</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                KyotoScribe is an AI-powered platform that transforms YouTube videos into various content formats including notes, study guides, presentations, and tutorials. Our service utilizes artificial intelligence to analyze video content and generate structured, educational materials.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. User Accounts and Registration</h2>
              <div className="text-gray-700 dark:text-gray-300 leading-relaxed space-y-3">
                <p>
                  To access certain features of our Service, you may be required to create an account. You must be at least 13 years of age to use our Service. You agree to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Provide accurate, current, and complete information during registration</li>
                  <li>Maintain and promptly update your account information</li>
                  <li>Maintain the security of your password and account</li>
                  <li>Accept all risks of unauthorized access to your account</li>
                  <li>Notify us immediately of any suspected unauthorized use of your account</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Acceptable Use Policy</h2>
              <div className="text-gray-700 dark:text-gray-300 leading-relaxed space-y-3">
                <p>You agree not to use the Service to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Upload, post, or transmit any content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable</li>
                  <li>Process videos that infringe upon the intellectual property rights of others</li>
                  <li>Attempt to gain unauthorized access to our systems or networks</li>
                  <li>Use the Service for any commercial purpose without our express written consent</li>
                  <li>Interfere with or disrupt the Service or servers or networks connected to the Service</li>
                  <li>Use the Service to process content that contains personal information of individuals without proper consent</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Content and Intellectual Property</h2>
              <div className="text-gray-700 dark:text-gray-300 leading-relaxed space-y-3">
                <p>
                  <strong>Your Content:</strong> You retain ownership of any content you submit to our Service. By using our Service, you grant us a non-exclusive, worldwide, royalty-free license to use, reproduce, and process your content solely for the purpose of providing our Service to you.
                </p>
                <p>
                  <strong>Generated Content:</strong> Content generated by our AI service based on your input is provided to you for your personal use. You are responsible for ensuring that your use of this generated content complies with applicable laws and respects the rights of others.
                </p>
                <p>
                  <strong>Service Content:</strong> The Service and its original content, features, and functionality are and will remain the exclusive property of KyotoScribe and its licensors.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">6. Subscription and Payment</h2>
              <div className="text-gray-700 dark:text-gray-300 leading-relaxed space-y-3">
                <p>
                  Certain features of the Service may require payment. By subscribing to a paid plan:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You agree to pay all fees associated with your chosen subscription plan</li>
                  <li>Subscription fees are billed in advance on a recurring basis</li>
                  <li>You may cancel your subscription at any time through Polar.sh or by contacting support</li>
                  <li>Refunds are handled in accordance with our refund policy</li>
                  <li>We reserve the right to change our pricing with reasonable notice</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">7. Privacy</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the Service, to understand our practices regarding the collection and use of your information.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">8. Disclaimers and Limitations of Liability</h2>
              <div className="text-gray-700 dark:text-gray-300 leading-relaxed space-y-3">
                <p>
                  <strong>Service Availability:</strong> We strive to maintain the Service's availability but cannot guarantee uninterrupted access. The Service is provided "as is" without warranties of any kind.
                </p>
                <p>
                  <strong>AI-Generated Content:</strong> Content generated by our AI service is for informational purposes only. We do not guarantee the accuracy, completeness, or reliability of AI-generated content.
                </p>
                <p>
                  <strong>Limitation of Liability:</strong> To the maximum extent permitted by law, KyotoScribe shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">9. Indemnification</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                You agree to defend, indemnify, and hold harmless KyotoScribe, its officers, directors, employees, and agents from and against any claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from your use of and access to the Service or your violation of these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">10. Termination</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. You may also terminate your account at any time by contacting us or using the account deletion features in your account settings.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">11. Changes to Terms</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect. Your continued use of the Service after such modifications constitutes your acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">12. Governing Law</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                These Terms shall be interpreted and governed by the laws of Delaware, United States, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">13. Contact Information</h2>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                If you have any questions about these Terms of Service, please contact us through our support channels available in the application or website.
              </p>
            </section>

            <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 mt-8">
              <p className="text-sm text-gray-600 dark:text-gray-300 text-center">
                These Terms of Service are effective as of September 2025 and apply to all users of the KyotoScribe service.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}